/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedJoinRouteImport } from './routes/_authenticated/join'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedPaymentsNewRouteImport } from './routes/_authenticated/payments.new'
import { Route as AuthenticatedPaymentsPaymentIdRouteImport } from './routes/_authenticated/payments.$paymentId'
import { Route as AuthenticatedGroupsTeamIdRouteImport } from './routes/_authenticated/groups.$teamId'
import { Route as AuthenticatedEventsNewRouteImport } from './routes/_authenticated/events.new'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events.$eventId'
import { Route as AuthenticatedClubsNewRouteImport } from './routes/_authenticated/clubs.new'
import { Route as AuthenticatedGroupsTeamIdIndexRouteImport } from './routes/_authenticated/groups.$teamId.index'
import { Route as AuthenticatedGroupsTeamIdSettingsRouteImport } from './routes/_authenticated/groups.$teamId.settings'
import { Route as AuthenticatedGroupsTeamIdPostsRouteImport } from './routes/_authenticated/groups.$teamId.posts'
import { Route as AuthenticatedGroupsTeamIdPollsRouteImport } from './routes/_authenticated/groups.$teamId.polls'
import { Route as AuthenticatedGroupsTeamIdPaymentsRouteImport } from './routes/_authenticated/groups.$teamId.payments'
import { Route as AuthenticatedGroupsTeamIdMembersRouteImport } from './routes/_authenticated/groups.$teamId.members'
import { Route as AuthenticatedGroupsTeamIdEventsRouteImport } from './routes/_authenticated/groups.$teamId.events'
import { Route as AuthenticatedClubsClubIdTeamsNewRouteImport } from './routes/_authenticated/clubs.$clubId.teams.new'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJoinRoute = AuthenticatedJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsNewRoute =
  AuthenticatedPaymentsNewRouteImport.update({
    id: '/payments/new',
    path: '/payments/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentsPaymentIdRoute =
  AuthenticatedPaymentsPaymentIdRouteImport.update({
    id: '/payments/$paymentId',
    path: '/payments/$paymentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsTeamIdRoute =
  AuthenticatedGroupsTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => AuthenticatedGroupsRoute,
  } as any)
const AuthenticatedEventsNewRoute = AuthenticatedEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClubsNewRoute = AuthenticatedClubsNewRouteImport.update({
  id: '/clubs/new',
  path: '/clubs/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGroupsTeamIdIndexRoute =
  AuthenticatedGroupsTeamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGroupsTeamIdRoute,
  } as any)
const AuthenticatedGroupsTeamIdSettingsRoute =
  AuthenticatedGroupsTeamIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedGroupsTeamIdRoute,
  } as any)
const AuthenticatedGroupsTeamIdPostsRoute =
  AuthenticatedGroupsTeamIdPostsRouteImport.update({
    id: '/posts',
    path: '/posts',
    getParentRoute: () => AuthenticatedGroupsTeamIdRoute,
  } as any)
const AuthenticatedGroupsTeamIdPollsRoute =
  AuthenticatedGroupsTeamIdPollsRouteImport.update({
    id: '/polls',
    path: '/polls',
    getParentRoute: () => AuthenticatedGroupsTeamIdRoute,
  } as any)
const AuthenticatedGroupsTeamIdPaymentsRoute =
  AuthenticatedGroupsTeamIdPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedGroupsTeamIdRoute,
  } as any)
const AuthenticatedGroupsTeamIdMembersRoute =
  AuthenticatedGroupsTeamIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedGroupsTeamIdRoute,
  } as any)
const AuthenticatedGroupsTeamIdEventsRoute =
  AuthenticatedGroupsTeamIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedGroupsTeamIdRoute,
  } as any)
const AuthenticatedClubsClubIdTeamsNewRoute =
  AuthenticatedClubsClubIdTeamsNewRouteImport.update({
    id: '/clubs/$clubId/teams/new',
    path: '/clubs/$clubId/teams/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/join': typeof AuthenticatedJoinRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/clubs/new': typeof AuthenticatedClubsNewRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/groups/$teamId': typeof AuthenticatedGroupsTeamIdRouteWithChildren
  '/payments/$paymentId': typeof AuthenticatedPaymentsPaymentIdRoute
  '/payments/new': typeof AuthenticatedPaymentsNewRoute
  '/groups/$teamId/events': typeof AuthenticatedGroupsTeamIdEventsRoute
  '/groups/$teamId/members': typeof AuthenticatedGroupsTeamIdMembersRoute
  '/groups/$teamId/payments': typeof AuthenticatedGroupsTeamIdPaymentsRoute
  '/groups/$teamId/polls': typeof AuthenticatedGroupsTeamIdPollsRoute
  '/groups/$teamId/posts': typeof AuthenticatedGroupsTeamIdPostsRoute
  '/groups/$teamId/settings': typeof AuthenticatedGroupsTeamIdSettingsRoute
  '/groups/$teamId/': typeof AuthenticatedGroupsTeamIdIndexRoute
  '/clubs/$clubId/teams/new': typeof AuthenticatedClubsClubIdTeamsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/join': typeof AuthenticatedJoinRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/clubs/new': typeof AuthenticatedClubsNewRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/payments/$paymentId': typeof AuthenticatedPaymentsPaymentIdRoute
  '/payments/new': typeof AuthenticatedPaymentsNewRoute
  '/groups/$teamId/events': typeof AuthenticatedGroupsTeamIdEventsRoute
  '/groups/$teamId/members': typeof AuthenticatedGroupsTeamIdMembersRoute
  '/groups/$teamId/payments': typeof AuthenticatedGroupsTeamIdPaymentsRoute
  '/groups/$teamId/polls': typeof AuthenticatedGroupsTeamIdPollsRoute
  '/groups/$teamId/posts': typeof AuthenticatedGroupsTeamIdPostsRoute
  '/groups/$teamId/settings': typeof AuthenticatedGroupsTeamIdSettingsRoute
  '/groups/$teamId': typeof AuthenticatedGroupsTeamIdIndexRoute
  '/clubs/$clubId/teams/new': typeof AuthenticatedClubsClubIdTeamsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/join': typeof AuthenticatedJoinRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/clubs/new': typeof AuthenticatedClubsNewRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/_authenticated/events/new': typeof AuthenticatedEventsNewRoute
  '/_authenticated/groups/$teamId': typeof AuthenticatedGroupsTeamIdRouteWithChildren
  '/_authenticated/payments/$paymentId': typeof AuthenticatedPaymentsPaymentIdRoute
  '/_authenticated/payments/new': typeof AuthenticatedPaymentsNewRoute
  '/_authenticated/groups/$teamId/events': typeof AuthenticatedGroupsTeamIdEventsRoute
  '/_authenticated/groups/$teamId/members': typeof AuthenticatedGroupsTeamIdMembersRoute
  '/_authenticated/groups/$teamId/payments': typeof AuthenticatedGroupsTeamIdPaymentsRoute
  '/_authenticated/groups/$teamId/polls': typeof AuthenticatedGroupsTeamIdPollsRoute
  '/_authenticated/groups/$teamId/posts': typeof AuthenticatedGroupsTeamIdPostsRoute
  '/_authenticated/groups/$teamId/settings': typeof AuthenticatedGroupsTeamIdSettingsRoute
  '/_authenticated/groups/$teamId/': typeof AuthenticatedGroupsTeamIdIndexRoute
  '/_authenticated/clubs/$clubId/teams/new': typeof AuthenticatedClubsClubIdTeamsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/groups'
    | '/home'
    | '/join'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/clubs/new'
    | '/events/$eventId'
    | '/events/new'
    | '/groups/$teamId'
    | '/payments/$paymentId'
    | '/payments/new'
    | '/groups/$teamId/events'
    | '/groups/$teamId/members'
    | '/groups/$teamId/payments'
    | '/groups/$teamId/polls'
    | '/groups/$teamId/posts'
    | '/groups/$teamId/settings'
    | '/groups/$teamId/'
    | '/clubs/$clubId/teams/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/groups'
    | '/home'
    | '/join'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/clubs/new'
    | '/events/$eventId'
    | '/events/new'
    | '/payments/$paymentId'
    | '/payments/new'
    | '/groups/$teamId/events'
    | '/groups/$teamId/members'
    | '/groups/$teamId/payments'
    | '/groups/$teamId/polls'
    | '/groups/$teamId/posts'
    | '/groups/$teamId/settings'
    | '/groups/$teamId'
    | '/clubs/$clubId/teams/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/groups'
    | '/_authenticated/home'
    | '/_authenticated/join'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/clubs/new'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/events/new'
    | '/_authenticated/groups/$teamId'
    | '/_authenticated/payments/$paymentId'
    | '/_authenticated/payments/new'
    | '/_authenticated/groups/$teamId/events'
    | '/_authenticated/groups/$teamId/members'
    | '/_authenticated/groups/$teamId/payments'
    | '/_authenticated/groups/$teamId/polls'
    | '/_authenticated/groups/$teamId/posts'
    | '/_authenticated/groups/$teamId/settings'
    | '/_authenticated/groups/$teamId/'
    | '/_authenticated/clubs/$clubId/teams/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/join': {
      id: '/_authenticated/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthenticatedJoinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments/new': {
      id: '/_authenticated/payments/new'
      path: '/payments/new'
      fullPath: '/payments/new'
      preLoaderRoute: typeof AuthenticatedPaymentsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments/$paymentId': {
      id: '/_authenticated/payments/$paymentId'
      path: '/payments/$paymentId'
      fullPath: '/payments/$paymentId'
      preLoaderRoute: typeof AuthenticatedPaymentsPaymentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/$teamId': {
      id: '/_authenticated/groups/$teamId'
      path: '/$teamId'
      fullPath: '/groups/$teamId'
      preLoaderRoute: typeof AuthenticatedGroupsTeamIdRouteImport
      parentRoute: typeof AuthenticatedGroupsRoute
    }
    '/_authenticated/events/new': {
      id: '/_authenticated/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthenticatedEventsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clubs/new': {
      id: '/_authenticated/clubs/new'
      path: '/clubs/new'
      fullPath: '/clubs/new'
      preLoaderRoute: typeof AuthenticatedClubsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/$teamId/': {
      id: '/_authenticated/groups/$teamId/'
      path: '/'
      fullPath: '/groups/$teamId/'
      preLoaderRoute: typeof AuthenticatedGroupsTeamIdIndexRouteImport
      parentRoute: typeof AuthenticatedGroupsTeamIdRoute
    }
    '/_authenticated/groups/$teamId/settings': {
      id: '/_authenticated/groups/$teamId/settings'
      path: '/settings'
      fullPath: '/groups/$teamId/settings'
      preLoaderRoute: typeof AuthenticatedGroupsTeamIdSettingsRouteImport
      parentRoute: typeof AuthenticatedGroupsTeamIdRoute
    }
    '/_authenticated/groups/$teamId/posts': {
      id: '/_authenticated/groups/$teamId/posts'
      path: '/posts'
      fullPath: '/groups/$teamId/posts'
      preLoaderRoute: typeof AuthenticatedGroupsTeamIdPostsRouteImport
      parentRoute: typeof AuthenticatedGroupsTeamIdRoute
    }
    '/_authenticated/groups/$teamId/polls': {
      id: '/_authenticated/groups/$teamId/polls'
      path: '/polls'
      fullPath: '/groups/$teamId/polls'
      preLoaderRoute: typeof AuthenticatedGroupsTeamIdPollsRouteImport
      parentRoute: typeof AuthenticatedGroupsTeamIdRoute
    }
    '/_authenticated/groups/$teamId/payments': {
      id: '/_authenticated/groups/$teamId/payments'
      path: '/payments'
      fullPath: '/groups/$teamId/payments'
      preLoaderRoute: typeof AuthenticatedGroupsTeamIdPaymentsRouteImport
      parentRoute: typeof AuthenticatedGroupsTeamIdRoute
    }
    '/_authenticated/groups/$teamId/members': {
      id: '/_authenticated/groups/$teamId/members'
      path: '/members'
      fullPath: '/groups/$teamId/members'
      preLoaderRoute: typeof AuthenticatedGroupsTeamIdMembersRouteImport
      parentRoute: typeof AuthenticatedGroupsTeamIdRoute
    }
    '/_authenticated/groups/$teamId/events': {
      id: '/_authenticated/groups/$teamId/events'
      path: '/events'
      fullPath: '/groups/$teamId/events'
      preLoaderRoute: typeof AuthenticatedGroupsTeamIdEventsRouteImport
      parentRoute: typeof AuthenticatedGroupsTeamIdRoute
    }
    '/_authenticated/clubs/$clubId/teams/new': {
      id: '/_authenticated/clubs/$clubId/teams/new'
      path: '/clubs/$clubId/teams/new'
      fullPath: '/clubs/$clubId/teams/new'
      preLoaderRoute: typeof AuthenticatedClubsClubIdTeamsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedGroupsTeamIdRouteChildren {
  AuthenticatedGroupsTeamIdEventsRoute: typeof AuthenticatedGroupsTeamIdEventsRoute
  AuthenticatedGroupsTeamIdMembersRoute: typeof AuthenticatedGroupsTeamIdMembersRoute
  AuthenticatedGroupsTeamIdPaymentsRoute: typeof AuthenticatedGroupsTeamIdPaymentsRoute
  AuthenticatedGroupsTeamIdPollsRoute: typeof AuthenticatedGroupsTeamIdPollsRoute
  AuthenticatedGroupsTeamIdPostsRoute: typeof AuthenticatedGroupsTeamIdPostsRoute
  AuthenticatedGroupsTeamIdSettingsRoute: typeof AuthenticatedGroupsTeamIdSettingsRoute
  AuthenticatedGroupsTeamIdIndexRoute: typeof AuthenticatedGroupsTeamIdIndexRoute
}

const AuthenticatedGroupsTeamIdRouteChildren: AuthenticatedGroupsTeamIdRouteChildren =
  {
    AuthenticatedGroupsTeamIdEventsRoute: AuthenticatedGroupsTeamIdEventsRoute,
    AuthenticatedGroupsTeamIdMembersRoute:
      AuthenticatedGroupsTeamIdMembersRoute,
    AuthenticatedGroupsTeamIdPaymentsRoute:
      AuthenticatedGroupsTeamIdPaymentsRoute,
    AuthenticatedGroupsTeamIdPollsRoute: AuthenticatedGroupsTeamIdPollsRoute,
    AuthenticatedGroupsTeamIdPostsRoute: AuthenticatedGroupsTeamIdPostsRoute,
    AuthenticatedGroupsTeamIdSettingsRoute:
      AuthenticatedGroupsTeamIdSettingsRoute,
    AuthenticatedGroupsTeamIdIndexRoute: AuthenticatedGroupsTeamIdIndexRoute,
  }

const AuthenticatedGroupsTeamIdRouteWithChildren =
  AuthenticatedGroupsTeamIdRoute._addFileChildren(
    AuthenticatedGroupsTeamIdRouteChildren,
  )

interface AuthenticatedGroupsRouteChildren {
  AuthenticatedGroupsTeamIdRoute: typeof AuthenticatedGroupsTeamIdRouteWithChildren
}

const AuthenticatedGroupsRouteChildren: AuthenticatedGroupsRouteChildren = {
  AuthenticatedGroupsTeamIdRoute: AuthenticatedGroupsTeamIdRouteWithChildren,
}

const AuthenticatedGroupsRouteWithChildren =
  AuthenticatedGroupsRoute._addFileChildren(AuthenticatedGroupsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedJoinRoute: typeof AuthenticatedJoinRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedClubsNewRoute: typeof AuthenticatedClubsNewRoute
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRoute
  AuthenticatedEventsNewRoute: typeof AuthenticatedEventsNewRoute
  AuthenticatedPaymentsPaymentIdRoute: typeof AuthenticatedPaymentsPaymentIdRoute
  AuthenticatedPaymentsNewRoute: typeof AuthenticatedPaymentsNewRoute
  AuthenticatedClubsClubIdTeamsNewRoute: typeof AuthenticatedClubsClubIdTeamsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGroupsRoute: AuthenticatedGroupsRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedJoinRoute: AuthenticatedJoinRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedClubsNewRoute: AuthenticatedClubsNewRoute,
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRoute,
  AuthenticatedEventsNewRoute: AuthenticatedEventsNewRoute,
  AuthenticatedPaymentsPaymentIdRoute: AuthenticatedPaymentsPaymentIdRoute,
  AuthenticatedPaymentsNewRoute: AuthenticatedPaymentsNewRoute,
  AuthenticatedClubsClubIdTeamsNewRoute: AuthenticatedClubsClubIdTeamsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
